# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 186bdfc469749e44fd375cd7d32f16a768f36c1956a6b6722adbe517b165c2d3376a9eb90633f4e4f6546f8e97d80b760de1876f6c1dcf7d12c18b5078223fe9

test:
  secret_key_base: 241c38fb110cfef935b2ce0b57d957e42a3e69ff1ec4f68f01f85b0e0e5848bc646b2ca812742aaefcae1d9021665898ad2ad86725cfd9480370eb23951dd149

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
